# Generated by Django 3.0.2 on 2020-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
                ('ConfirmPassword', models.TextField()),
            ],
        ),
    ]
