# Generated by Django 3.0.2 on 2020-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200224_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
                ('Confirm', models.TextField()),
                ('Aadhar', models.TextField()),
                ('Code', models.IntegerField()),
                ('PhoneNo', models.IntegerField()),
                ('Address', models.TextField()),
            ],
        ),
    ]
