# Generated by Django 3.0.2 on 2020-03-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfo',
            name='Username',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinfo',
            name='Username',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
