# Generated by Django 3.0.2 on 2020-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_food_vendoradd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoradd',
            name='food',
        ),
        migrations.AddField(
            model_name='vendoradd',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendoradd',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendoradd',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
