# Generated by Django 3.0.2 on 2020-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200327_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinfo',
            name='Dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
