# Generated by Django 3.0.2 on 2020-04-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_vinfo_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinfo',
            name='Kitchen',
            field=models.TextField(default='mohini'),
            preserve_default=False,
        ),
    ]
