# Generated by Django 3.0.2 on 2020-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200420_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinfo',
            name='Confirm',
        ),
        migrations.RemoveField(
            model_name='cinfo',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='cinfo',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='vinfo',
            name='Confirm',
        ),
        migrations.RemoveField(
            model_name='vinfo',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='vinfo',
            name='Lastname',
        ),
        migrations.AddField(
            model_name='cinfo',
            name='Aadhar',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinfo',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cinfo',
            name='Name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinfo',
            name='Name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinfo',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cinfo',
            name='Password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cinfo',
            name='Username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Aadhar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Kitchen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Username',
            field=models.CharField(max_length=255),
        ),
    ]
