# Generated by Django 3.0.2 on 2020-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200513_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfo',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
