# Generated by Django 3.0.2 on 2020-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200513_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfo',
            name='Address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Address',
            field=models.CharField(max_length=1000),
        ),
    ]
