# Generated by Django 3.0.2 on 2020-05-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='placed', max_length=10),
        ),
    ]
