# Generated by Django 3.0.2 on 2020-05-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
