# Generated by Django 3.0.2 on 2020-05-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
