# Generated by Django 3.0.2 on 2020-05-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('customer_username', models.CharField(max_length=255)),
                ('vendor_username', models.CharField(max_length=255)),
                ('ordered_items', models.CharField(max_length=5000)),
                ('grandTotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=10)),
                ('phoneNo', models.IntegerField()),
                ('paymentMode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('placed', 'placed'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='placed', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='home.Cinfo')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='home.Vinfo')),
            ],
        ),
    ]
