# Generated by Django 3.0.2 on 2020-05-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinfo',
            name='Aadhar',
        ),
    ]
