# Generated by Django 3.0.2 on 2020-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200531_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfo',
            name='PhoneNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='phoneNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='PhoneNo',
            field=models.CharField(max_length=12),
        ),
    ]
