# Generated by Django 3.0.2 on 2020-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200531_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfo',
            name='Image',
            field=models.ImageField(blank=True, default='https://img.icons8.com/plasticine/2x/user.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Image',
            field=models.ImageField(blank=True, default='https://www.canva.com/learn/wp-content/uploads/2018/06/FoodPhotographyProps34-tb-1320x743.jpg', null=True, upload_to='images/'),
        ),
    ]
