# Generated by Django 3.0.2 on 2020-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200605_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfo',
            name='Image',
            field=models.ImageField(blank=True, default='images/customer/profile/default-customer.png', null=True, upload_to='images/customer/profile/'),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Image',
            field=models.ImageField(blank=True, default='images/vendor/profile/default-vendor.PNG', null=True, upload_to='images/vendor/profile/'),
        ),
    ]
